apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-app.fullname" . }}-config
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
data:
  app-config.yaml: |
    app:
      name: {{ .Values.config.appName }}
      environment: {{ .Values.config.environment }}
      logLevel: {{ .Values.config.logLevel }}
    
    server:
      port: 80
      host: "0.0.0.0"
